/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { DrizzleToZeroSchema } from "drizzle-zero";
import type * as DrizzleZeroTypes from "./drizzle/schema";

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    allTypes: {
      name: "allTypes",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["createdAt"]["customType"],
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["updatedAt"]["customType"],
        },
        id: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["id"]["customType"],
        },
        smallintField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["smallintField"]["customType"],
          serverName: "smallint",
        },
        integerField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["integerField"]["customType"],
          serverName: "integer",
        },
        bigintField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["bigintField"]["customType"],
          serverName: "bigint",
        },
        bigintNumberField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["bigintNumberField"]["customType"],
          serverName: "bigint_number",
        },
        smallSerialField: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["smallSerialField"]["customType"],
          serverName: "smallserial",
        },
        serialField: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["serialField"]["customType"],
          serverName: "serial",
        },
        bigSerialField: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["bigSerialField"]["customType"],
          serverName: "bigserial",
        },
        numericField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["numericField"]["customType"],
          serverName: "numeric",
        },
        decimalField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["decimalField"]["customType"],
          serverName: "decimal",
        },
        realField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["realField"]["customType"],
          serverName: "real",
        },
        doublePrecisionField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["doublePrecisionField"]["customType"],
          serverName: "double_precision",
        },
        textField: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["textField"]["customType"],
          serverName: "text",
        },
        charField: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["charField"]["customType"],
          serverName: "char",
        },
        uuidField: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["uuidField"]["customType"],
          serverName: "uuid",
        },
        varcharField: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["varcharField"]["customType"],
          serverName: "varchar",
        },
        booleanField: {
          type: "boolean",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["booleanField"]["customType"],
          serverName: "boolean",
        },
        timestampField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["timestampField"]["customType"],
          serverName: "timestamp",
        },
        timestampTzField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["timestampTzField"]["customType"],
          serverName: "timestamp_tz",
        },
        timestampModeString: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["timestampModeString"]["customType"],
          serverName: "timestamp_mode_string",
        },
        timestampModeDate: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["timestampModeDate"]["customType"],
          serverName: "timestamp_mode_date",
        },
        dateField: {
          type: "number",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["dateField"]["customType"],
          serverName: "date",
        },
        jsonField: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["jsonField"]["customType"],
          serverName: "json",
        },
        jsonbField: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["jsonbField"]["customType"],
          serverName: "jsonb",
        },
        typedJsonField: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["typedJsonField"]["customType"],
          serverName: "typed_json",
        },
        statusField: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["statusField"]["customType"],
          serverName: "status",
        },
        optionalSmallint: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalSmallint"]["customType"],
          serverName: "optional_smallint",
        },
        optionalInteger: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalInteger"]["customType"],
          serverName: "optional_integer",
        },
        optionalBigint: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalBigint"]["customType"],
          serverName: "optional_bigint",
        },
        optionalNumeric: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalNumeric"]["customType"],
          serverName: "optional_numeric",
        },
        optionalReal: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalReal"]["customType"],
          serverName: "optional_real",
        },
        optionalDoublePrecision: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalDoublePrecision"]["customType"],
          serverName: "optional_double_precision",
        },
        optionalText: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalText"]["customType"],
          serverName: "optional_text",
        },
        optionalBoolean: {
          type: "boolean",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalBoolean"]["customType"],
          serverName: "optional_boolean",
        },
        optionalTimestamp: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalTimestamp"]["customType"],
          serverName: "optional_timestamp",
        },
        optionalJson: {
          type: "json",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalJson"]["customType"],
          serverName: "optional_json",
        },
        optionalEnum: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalEnum"]["customType"],
          serverName: "optional_enum",
        },
        optionalVarchar: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalVarchar"]["customType"],
          serverName: "optional_varchar",
        },
        optionalUuid: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["allTypes"]["columns"]["optionalUuid"]["customType"],
          serverName: "optional_uuid",
        },
      },
      primaryKey: ["id"],
      serverName: "all_types",
    },
    filters: {
      name: "filters",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["filters"]["columns"]["id"]["customType"],
        },
        name: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["filters"]["columns"]["name"]["customType"],
        },
        parentId: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["filters"]["columns"]["parentId"]["customType"],
          serverName: "parent_id",
        },
      },
      primaryKey: ["id"],
    },
    friendship: {
      name: "friendship",
      columns: {
        requestingId: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["friendship"]["columns"]["requestingId"]["customType"],
        },
        acceptingId: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["friendship"]["columns"]["acceptingId"]["customType"],
        },
        accepted: {
          type: "boolean",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["friendship"]["columns"]["accepted"]["customType"],
        },
      },
      primaryKey: ["requestingId", "acceptingId"],
    },
    medium: {
      name: "medium",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["medium"]["columns"]["createdAt"]["customType"],
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["medium"]["columns"]["updatedAt"]["customType"],
        },
        id: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["medium"]["columns"]["id"]["customType"],
        },
        name: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["medium"]["columns"]["name"]["customType"],
        },
      },
      primaryKey: ["id"],
    },
    message: {
      name: "message",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["createdAt"]["customType"],
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["updatedAt"]["customType"],
        },
        id: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["id"]["customType"],
        },
        senderId: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["senderId"]["customType"],
        },
        mediumId: {
          type: "string",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["mediumId"]["customType"],
        },
        body: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["body"]["customType"],
        },
        metadata: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["message"]["columns"]["metadata"]["customType"],
        },
      },
      primaryKey: ["id"],
    },
    user: {
      name: "user",
      columns: {
        createdAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["createdAt"]["customType"],
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["updatedAt"]["customType"],
        },
        id: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["id"]["customType"],
        },
        name: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["name"]["customType"],
        },
        partner: {
          type: "boolean",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["partner"]["customType"],
        },
        email: {
          type: "string",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["email"]["customType"],
        },
        customTypeJson: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["customTypeJson"]["customType"],
          serverName: "custom_type_json",
        },
        customInterfaceJson: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["customInterfaceJson"]["customType"],
          serverName: "custom_interface_json",
        },
        testInterface: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["testInterface"]["customType"],
          serverName: "test_interface",
        },
        testType: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["testType"]["customType"],
          serverName: "test_type",
        },
        testExportedType: {
          type: "json",
          optional: false,
          customType: null as DrizzleToZeroSchema<
            typeof DrizzleZeroTypes
          >["tables"]["user"]["columns"]["testExportedType"]["customType"],
          serverName: "test_exported_type",
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    filters: {
      parent: [
        {
          sourceField: ["parentId"],
          destField: ["id"],
          destSchema: "filters",
          cardinality: "one",
        },
      ],
      children: [
        {
          sourceField: ["id"],
          destField: ["parentId"],
          destSchema: "filters",
          cardinality: "many",
        },
      ],
    },
    medium: {
      messages: [
        {
          sourceField: ["id"],
          destField: ["mediumId"],
          destSchema: "message",
          cardinality: "many",
        },
      ],
    },
    message: {
      medium: [
        {
          sourceField: ["mediumId"],
          destField: ["id"],
          destSchema: "medium",
          cardinality: "one",
        },
      ],
      sender: [
        {
          sourceField: ["senderId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
    },
    user: {
      messages: [
        {
          sourceField: ["id"],
          destField: ["senderId"],
          destSchema: "message",
          cardinality: "many",
        },
      ],
    },
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
